#!/usr/bin/env python3
import rospy
from migrave_performance_tracking_wrapper.performance_tracking_wrapper import PerformanceTrackingWrapper

if __name__ == '__main__':
    rospy.init_node('game_performance_tracking')
    performance_tracking = PerformanceTrackingWrapper()
    try:
        while not rospy.is_shutdown():
            performance_tracking.act()
            rospy.sleep(5)
    except rospy.ROSInterruptException as exc:
        print('performance_tracking ...')
